name       : ding
version    : 1.8.1
release    : 2
source     :
    - http://ftp.tu-chemnitz.de/pub/Local/urz/ding/ding-1.8.1.tar.gz : 5817bad70d9661fc1efc8bad38939bf665818c549a9675e8e041fff487c61232
license    : GPL-2.0
component  : office
summary    : Ding is a Dictionary lookup program for the X window system. It comes with a German-English Dictionary with approximately 326,000 entries.
description: |
    Ding is a Dictionary lookup program for the X window system. It comes with a German-English Dictionary with approximately 326,000 entries.
rundeps    :
    - tk
    - hunspell-de
    - hunspell-en
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-names-of-executables.patch
install    : |
    install -Dm755 ding $installdir/usr/bin/ding
    install -Dm644 de-en.txt $installdir/usr/share/dict/de-en.txt
    install -Dm644 ding.1 $installdir/usr/share/man/man1/ding.1
    install -Dm644 ding.desktop $installdir/usr/share/applications/ding.desktop
    install -Dm644 ding.png $installdir/usr/share/icons/hicolor/32x32/apps/ding.png
